name: siarna
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - pip
  - viennarna=2.4.7
  - numpy
  - pip:
      - asttokens==3.0.0
      - bio==1.8.0
      - biopython==1.85
      - biothings_client==0.4.1
      - blinker==1.9.0
      - certifi==2025.10.5
      - charset-normalizer==3.4.3
      - click==8.3.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - decorator==5.2.1
      - dill==0.4.0
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - filelock==3.13.1
      - flask==3.1.2
      - fonttools==4.60.1
      - fsspec==2024.6.1
      - gprofiler-official==1.0.0
      - gunicorn==23.0.0
      - hf-xet==1.1.10
      - huggingface-hub==0.35.3
      - idna==3.10
      - ipython==8.37.0
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - llvmlite==0.45.1
      - lxml==6.0.2
      - markupsafe==3.0.3
      - matplotlib==3.10.6
      - matplotlib-inline==0.1.7
      - mpmath==1.3.0
      - mygene==3.2.2
      - narwhals==2.7.0
      - networkx==3.3
      - numba==0.62.1
      - pandas==2.3.3
      - pillow==11.0.0
      - platformdirs==4.4.0
      - plotly==6.3.1
      - pooch==1.8.2
      - prompt-toolkit==3.0.52
      - psutil==7.1.0
      - ptflops==0.7.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.19.2
      - pyhocon==0.3.61
      - pynndescent==0.5.13
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.9.18
      - requests==2.32.5
      - rna-fm==0.2.2
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - sentencepiece==0.2.1
      - stack-data==0.6.3
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.57.0
      - umap-learn==0.5.9.post2
      - urllib3==2.5.0
      - wcwidth==0.2.14
      - werkzeug==3.1.3
